# Generated by Django 6.0.7 on 2026-07-17 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eleve',
            name='extra_data',
            field=models.JSONField(blank=True, default=dict, help_text='Champs personnalisés additionnels (créés depuis un import ou la fiche élève).'),
        ),
    ]
