# Generated by Django 6.0.7 on 2026-07-17 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_eleve_extra_data'),
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomFieldDefinition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custom_fields', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
                'unique_together': {('school', 'slug')},
            },
        ),
    ]
