# Generated by Django 6.0.7 on 2026-07-17 08:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Parent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(db_index=True, max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international, ex: +2250700000000', regex='^\\+[1-9]\\d{6,14}$')])),
                ('whatsapp_number', models.CharField(blank=True, help_text='Laisser vide si identique au téléphone', max_length=20, validators=[django.core.validators.RegexValidator(message='Le numéro doit être au format international, ex: +2250700000000', regex='^\\+[1-9]\\d{6,14}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('preferred_channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email')], default='SMS', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
            },
        ),
        migrations.CreateModel(
            name='StudentGuardian',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship', models.CharField(choices=[('MERE', 'Mère'), ('PERE', 'Père'), ('TUTEUR', 'Tuteur/Tutrice'), ('AUTRE', 'Autre')], default='TUTEUR', max_length=10)),
                ('is_primary_contact', models.BooleanField(default=False, help_text="Contact prioritaire pour l'envoi des messages")),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parents.parent')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='academics.eleve')),
            ],
            options={
                'ordering': ['student', '-is_primary_contact'],
                'unique_together': {('student', 'parent')},
            },
        ),
        migrations.AddField(
            model_name='parent',
            name='students',
            field=models.ManyToManyField(related_name='parents', through='parents.StudentGuardian', to='academics.eleve'),
        ),
    ]
