# Generated by Django 6.0.7 on 2026-07-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='email_monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text="Nombre d'emails envoyables ce mois. Vide = illimité.", null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='quota_reset_at',
            field=models.DateTimeField(blank=True, help_text='Dernière réinitialisation manuelle des compteurs. Vide = seul le changement de mois calendaire remet les compteurs à zéro.', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='sms_monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de SMS envoyables ce mois. Vide = illimité.', null=True),
        ),
        migrations.AddField(
            model_name='school',
            name='whatsapp_monthly_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Nombre de messages WhatsApp envoyables ce mois. Vide = illimité.', null=True),
        ),
    ]
