# Generated by Django 6.0.7 on 2026-07-17 11:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0001_initial'),
        ('parents', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.TextField()),
                ('scope_type', models.CharField(choices=[('CLASSE', 'Classe'), ('NIVEAU', 'Niveau'), ('ECOLE', 'École entière'), ('INDIVIDUEL', 'Élève(s) individuel(s)')], max_length=20)),
                ('scope_level', models.CharField(blank=True, max_length=50)),
                ('channel', models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('AUTO', 'Automatique (canal préféré du parent)')], default='AUTO', max_length=10)),
                ('status', models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec')], default='BROUILLON', max_length=10)),
                ('recipient_count', models.PositiveIntegerField(default=0)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='schools.school')),
                ('scope_classe', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='academics.classe')),
                ('scope_eleves', models.ManyToManyField(blank=True, related_name='targeted_messages', to='academics.eleve')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageRecipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_used', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('ENVOYE', 'Envoyé'), ('ECHEC', 'Échec'), ('EN_ATTENTE', 'En attente')], default='EN_ATTENTE', max_length=10)),
                ('cost', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('eleve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages_about', to='academics.eleve')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipients', to='messaging.message')),
                ('parent', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='parents.parent')),
            ],
            options={
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('RESULTATS', 'Résultats'), ('ABSENCE', 'Absence'), ('PAIEMENT', 'Paiement'), ('REUNION', 'Réunion'), ('CONVOCATION', 'Convocation'), ('AUTRE', 'Autre')], default='AUTRE', max_length=20)),
                ('body', models.TextField(help_text='Variables disponibles : {parent_nom}, {eleve_nom}, {classe}, {ecole}')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_templates', to='schools.school')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='message',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='messaging.messagetemplate'),
        ),
    ]
