# Generated by Django 6.0.7 on 2026-07-19 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_customfielddefinition'),
        ('messaging', '0001_initial'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='retry_of',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='retries', to='messaging.message'),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('NO_PARENT', 'Aucun parent lié'), ('NO_CONTACT', 'Parent sans contact pour ce canal')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='message',
            name='status',
            field=models.CharField(choices=[('BROUILLON', 'Brouillon'), ('ENVOYE', 'Envoyé'), ('PARTIEL', 'Partiellement envoyé'), ('ECHEC', 'Échec')], default='BROUILLON', max_length=10),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='channel_used',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages_received', to='parents.parent'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'eleve')},
        ),
    ]
