# Generated by Django 6.0.7 on 2026-07-21 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_retry_of_messagerecipient_skip_reason_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='attempts',
            field=models.JSONField(blank=True, default=list, help_text="Canaux essayés dans l'ordre avant d'aboutir (mode cascade) : [{parent, parent_name, channel, status, error}]."),
        ),
        migrations.AlterField(
            model_name='message',
            name='channel',
            field=models.CharField(choices=[('SMS', 'SMS'), ('WHATSAPP', 'WhatsApp'), ('EMAIL', 'Email'), ('AUTO', 'Automatique (canal préféré du parent)'), ('CASCADE', 'Cascade (SMS, puis WhatsApp, puis Email)')], default='AUTO', max_length=10),
        ),
    ]
