# Generated by Django 6.0.7 on 2026-07-21 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0003_messagerecipient_attempts_alter_message_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='channel_order',
            field=models.JSONField(blank=True, default=list, help_text="Ordre de priorité des canaux quand channel=CASCADE, ex. ['SMS', 'EMAIL']. Vide = ordre par défaut (SMS, WhatsApp, Email)."),
        ),
        migrations.AlterField(
            model_name='messagerecipient',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('NO_PARENT', 'Aucun parent lié'), ('NO_CONTACT', 'Parent sans contact pour ce canal'), ('SEND_FAILED', 'Tous les canaux essayés ont échoué')], default='', max_length=20),
        ),
    ]
