# Generated by Django 6.0.7 on 2026-07-21 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_customfielddefinition'),
        ('messaging', '0004_message_channel_order_and_more'),
        ('parents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='notify_all_parents',
            field=models.BooleanField(default=False, help_text='Envoyer à tous les parents de chaque élève. Par défaut, seul le contact prioritaire (ou le premier parent joignable) est contacté.'),
        ),
        migrations.AlterUniqueTogether(
            name='messagerecipient',
            unique_together={('message', 'eleve', 'parent')},
        ),
    ]
