# Generated by Django 6.0.7 on 2026-07-21 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0005_message_notify_all_parents_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagerecipient',
            name='eleves_count',
            field=models.PositiveIntegerField(default=1, help_text="Nombre d'élèves couverts par ce message. Vaut plus de 1 quand un parent a plusieurs enfants concernés et que le message ne cite aucun élève."),
        ),
    ]
