# Generated by Django 6.0.7 on 2026-07-22 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0007_message_annee'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='subject',
            field=models.CharField(blank=True, help_text="Objet, utilisé par l'email uniquement. Vide = le nom de l'école.", max_length=200),
        ),
        migrations.AddField(
            model_name='messagerecipient',
            name='rendered_body',
            field=models.TextField(blank=True, help_text="Texte réellement envoyé à ce parent, variables substituées. Conservé pour pouvoir justifier après coup ce que l'établissement a envoyé."),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='subject',
            field=models.CharField(blank=True, help_text="Objet, utilisé par l'email uniquement. Vide = le nom de l'école.", max_length=200),
        ),
        migrations.AlterField(
            model_name='messagetemplate',
            name='body',
            field=models.TextField(help_text="Variables entre accolades, ex. {eleve_nom}. La liste complète dépend de l'école (les champs personnalisés en font partie) — voir GET /api/messages/variables/."),
        ),
    ]
