# Generated by Django 6.0.7 on 2026-07-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0008_message_subject_messagerecipient_rendered_body_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagerecipient',
            name='skip_reason',
            field=models.CharField(blank=True, choices=[('', 'N/A'), ('NO_PARENT', 'Aucun parent lié'), ('NO_CONTACT', 'Parent sans contact pour ce canal'), ('QUOTA_EXCEEDED', "Quota mensuel de l'école atteint"), ('SEND_FAILED', 'Tous les canaux essayés ont échoué')], default='', max_length=20),
        ),
    ]
