"""
Django settings for SchoolConnect project.

Generated by 'django-admin startproject' using Django 6.0.7.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

from pathlib import Path
import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env(DEBUG=(bool, False))
environ.Env.read_env(BASE_DIR / '.env')


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env('DEBUG')

ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['localhost', '127.0.0.1'])


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # third-party
    'rest_framework',
    'corsheaders',
    'anymail',
    # local apps (schools first: no dependencies; parents last: depends on academics)
    'schools',
    'accounts',
    'academics',
    'parents',
    'messaging',
    'data_import',
]

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'SchoolConnect.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'SchoolConnect.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

DATABASES = {
    'default': env.db('DATABASE_URL'),
}
# Connexions persistantes courtes + vérification de santé avant réutilisation :
# réduit l'overhead de reconnexion à chaque requête sans risquer une connexion
# périmée après une mise en veille du compute Neon (serverless).
DATABASES['default']['CONN_MAX_AGE'] = 60
DATABASES['default']['CONN_HEALTH_CHECKS'] = True

AUTH_USER_MODEL = 'accounts.User'

CORS_ALLOWED_ORIGINS = env.list('CORS_ALLOWED_ORIGINS', default=['http://localhost:5173'])
CORS_ALLOW_CREDENTIALS = True
CSRF_TRUSTED_ORIGINS = env.list('CSRF_TRUSTED_ORIGINS', default=['http://localhost:5173'])

# Base du frontend, utilisée pour construire le lien envoyé dans l'email de
# réinitialisation de mot de passe (accounts/views.py).
FRONTEND_URL = env('FRONTEND_URL', default='http://localhost:5173')

REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.SessionAuthentication',
    ],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.IsAuthenticated',
    ],
    'DEFAULT_PAGINATION_CLASS': 'rest_framework.pagination.PageNumberPagination',
    'PAGE_SIZE': 200,
}

# Email — Resend via django-anymail. Sans clé, Django retombe sur le backend console :
# les messages email s'affichent dans les logs au lieu de partir, ce qui garde le
# développement fonctionnel sans compte Resend.
RESEND_API_KEY = env('RESEND_API_KEY', default='')
ANYMAIL = {'RESEND_API_KEY': RESEND_API_KEY}
EMAIL_BACKEND = (
    'anymail.backends.resend.EmailBackend' if RESEND_API_KEY
    else 'django.core.mail.backends.console.EmailBackend'
)
# Doit appartenir à un domaine vérifié chez Resend, sinon l'envoi est refusé.
DEFAULT_FROM_EMAIL = env('DEFAULT_FROM_EMAIL', default='SchoolConnect <onboarding@resend.dev>')

# Canaux sans passerelle (SMS, WhatsApp) : 'fail' les fait échouer — la cascade retombe
# alors sur l'email, réellement envoyé — 'success' conserve l'ancienne simulation
# optimiste. L'aperçu applique la même règle, pour ne jamais annoncer un coût SMS sur un
# envoi qui finira en email (cf. messaging/services.py: is_wired).
SIMULATE_UNWIRED_CHANNELS = env('SIMULATE_UNWIRED_CHANNELS', default='fail')

# Import IA (data_import app) — proxy tiers HighwayAPI (compatible OpenAI),
# en attendant une vraie clé Anthropic officielle. Voir data_import/ai_parser.py.
AI_PROXY_API_KEY = env('AI_PROXY_API_KEY', default=None)
AI_PROXY_BASE_URL = env('AI_PROXY_BASE_URL', default='https://api.highwayapi.ai/openai')

# Celery
CELERY_BROKER_URL = env('CELERY_BROKER_URL', default='redis://localhost:6379/0')
CELERY_RESULT_BACKEND = env('CELERY_RESULT_BACKEND', default='redis://localhost:6379/0')
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
# Sans ça, le worker reconfigure le root logger avec sa propre config au démarrage et
# écrase LOGGING ci-dessous (cf. SchoolConnect/celery.py, qui applique LOGGING lui-même).
CELERY_WORKER_HIJACK_ROOT_LOGGER = False

# Logging — fichier + console partout (runserver et worker Celery). Sans ça, tout ce que
# services.py: logger.exception() écrit (échecs d'envoi email/SMS/WhatsApp, tâches
# Celery en échec) part uniquement dans le terminal courant et disparaît avec lui.
LOGS_DIR = BASE_DIR / 'logs'
LOGS_DIR.mkdir(exist_ok=True)

LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{asctime} {levelname} {name} — {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': LOGS_DIR / 'app.log',
            'maxBytes': 5 * 1024 * 1024,
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        # Sous-logger de 'django', mais explicite pour garder les 500 dans le fichier
        # même si la config de 'django' change plus tard.
        'django.request': {
            'handlers': ['console', 'file'],
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'fr'

TIME_ZONE = 'Africa/Abidjan'

USE_I18N = True

USE_TZ = True

CELERY_TIMEZONE = TIME_ZONE


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'
# Habillage de Django Admin (charte SchoolConnect) : voir static/admin/css et templates/admin.
STATICFILES_DIRS = [BASE_DIR / 'static']
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Fichiers temporaires (ex: import IA en attente de traitement par Celery)
MEDIA_URL = 'media/'
MEDIA_ROOT = BASE_DIR / 'media'
